# Generated by Django 3.0.5 on 2020-04-13 19:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrators', '0001_initial'),
        ('negotiations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bc_tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('bc_admin_type_investiment', models.ManyToManyField(to='administrators.bc_admin_type_investiment')),
                ('bc_admin_type_negotiation', models.ManyToManyField(to='administrators.bc_admin_type_negotiation')),
            ],
            options={
                'verbose_name': 'tax',
                'verbose_name_plural': 'taxes',
            },
        ),
        migrations.CreateModel(
            name='bc_tax_negotiation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('bc_negotiation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='negotiations.bc_negotiation')),
                ('bc_tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taxes.bc_tax')),
            ],
            options={
                'verbose_name': 'tax negotiation',
                'verbose_name_plural': 'taxes negotiations',
            },
        ),
    ]
