# Generated by Django 3.0.5 on 2020-04-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0001_initial'),
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bc_tax',
            name='bc_admin_type_investiment',
            field=models.ManyToManyField(blank=True, null=True, to='administrators.bc_admin_type_investiment'),
        ),
    ]
