# Generated by Django 3.0.5 on 2020-04-13 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bc_admin_type_investiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'admin type investiment',
                'verbose_name_plural': 'admin types investiments',
            },
        ),
        migrations.CreateModel(
            name='bc_admin_type_negotiation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'admin type negotiation',
                'verbose_name_plural': 'admin types negotiations',
            },
        ),
    ]
